name: Hexo Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Node
      uses: actions/setup-node@v5
      with:
        node-version: 24
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Generate Hexo
      run: npx hexo generate

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: hexo-public
        path: public
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v5
      with:
        name: hexo-public
        path: public

    - name: Setup Wrangler
      run: npm install -g wrangler

    - name: Deploy to Cloudflare Pages
      run: |
        wrangler pages deploy public \
        --project-name=blog
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}