name: Hexo Build

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Node
      uses: actions/setup-node@v5
      with:
        node-version-file: '.nvmrc'
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Inject Gitment OAuth
      run: |
        sed -i "s/\$GITMENT_CLIENT_ID/${{ secrets.GITMENT_CLIENT_ID }}/g" themes/yilia-plus/_config.yml
        sed -i "s/\$GITMENT_CLIENT_SECRET/${{ secrets.GITMENT_CLIENT_SECRET }}/g" themes/yilia-plus/_config.yml

    - name: Generate Hexo
      run: npx hexo generate

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: public
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4